function(encos_relay_ws_check out_available out_reason)
    if(NOT ENCOS_ENABLE_RELAY)
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "RelayWs plugin requires ENCOS_ENABLE_RELAY=ON" PARENT_SCOPE)
        return()
    endif()

    if(EMSCRIPTEN OR CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
        set(${out_available} TRUE PARENT_SCOPE)
        set(${out_reason} "" PARENT_SCOPE)
        return()
    endif()

    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "RelayWs plugin is only supported on Linux" PARENT_SCOPE)
        return()
    endif()

    if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/external/IXWebSocket/ixwebsocket/IXWebSocket.h")
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "IXWebSocket submodule is not initialized" PARENT_SCOPE)
        return()
    endif()

    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()

set(ENCOS_PLUGIN_CHECK_FUNCTION encos_relay_ws_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "RelayWs")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "RelayWsPlugin")
set(ENCOS_PLUGIN_STATIC_TARGET "RelayWsAdapterSupport")
set(ENCOS_PLUGIN_STATIC_HEADER "relayWs/relay_ws_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::CreateRelayWsAdapterStatic")
set(ENCOS_PLUGIN_VISIBLE ON)
