function(encos_can_check out_available out_reason)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "Can plugin is only supported on Linux" PARENT_SCOPE)
        return()
    endif()
    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()

set(ENCOS_PLUGIN_CHECK_FUNCTION encos_can_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "Can")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "CanPlugin")
set(ENCOS_PLUGIN_STATIC_TARGET "CanPluginCore")
set(ENCOS_PLUGIN_STATIC_HEADER "can/can_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::CanAdapter::Create")
set(ENCOS_PLUGIN_VISIBLE ON)
