function(encos_usb_serial_check out_available out_reason)
    if(NOT (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux" OR EMSCRIPTEN OR
            CMAKE_SYSTEM_NAME STREQUAL "Emscripten"))
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "UsbSerial requires Linux, Windows or Emscripten" PARENT_SCOPE)
        return()
    endif()
    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()

set(ENCOS_PLUGIN_CHECK_FUNCTION encos_usb_serial_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "UsbSerial")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "UsbSerialPlugin")
set(ENCOS_PLUGIN_STATIC_TARGET "UsbSerialPluginCore")
set(ENCOS_PLUGIN_STATIC_HEADER "usbSerial/usb_serial_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::UsbSerialAdapter::Create")
set(ENCOS_PLUGIN_VISIBLE ON)
