function(encos_ethercat_windows_check out_available out_reason)
    if(NOT WIN32)
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "EthercatWindows plugin is only supported on Windows" PARENT_SCOPE)
        return()
    endif()
    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()

set(ENCOS_PLUGIN_CHECK_FUNCTION encos_ethercat_windows_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "EthercatWindows")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "EthercatWindowsPlugin")
set(ENCOS_PLUGIN_STATIC_TARGET "EthercatWindowsPluginCore")
set(ENCOS_PLUGIN_STATIC_HEADER "ethercatWindows/ethercat_windows_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::EthercatWindowsAdapter::Create")
set(ENCOS_PLUGIN_VISIBLE ON)
