function(encos_ethernet_check out_available out_reason)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT WIN32)
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "Ethernet plugin is supported on Linux and Windows" PARENT_SCOPE)
        return()
    endif()
    if(WIN32)
        set(${out_available} TRUE PARENT_SCOPE)
        set(${out_reason} "" PARENT_SCOPE)
        return()
    endif()
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(ETHERNET_XDP QUIET libxdp libbpf)
    endif()
    find_program(ETHERNET_BPF_CLANG NAMES clang clang-20 clang-19 clang-18 clang-17 clang-16)
    if(NOT ETHERNET_XDP_FOUND OR NOT ETHERNET_BPF_CLANG)
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "Ethernet requires libxdp-dev, libbpf-dev and clang with BPF support" PARENT_SCOPE)
        return()
    endif()
    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()
set(ENCOS_PLUGIN_CHECK_FUNCTION encos_ethernet_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "Ethernet")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "EthernetPlugin")
set(ENCOS_PLUGIN_VISIBLE ON)
set(ENCOS_PLUGIN_STATIC_TARGET "EthernetAdapterSupport")
set(ENCOS_PLUGIN_STATIC_HEADER "ethernet/ethernet_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::CreateEthernetAdapterStatic")
