function(encos_ethercat_igh_check out_available out_reason)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "EthercatIGH plugin is only supported on Linux" PARENT_SCOPE)
        return()
    endif()
    find_package(IGHEtherCAT QUIET)
    if(NOT IGHEtherCAT_FOUND)
        set(${out_available} FALSE PARENT_SCOPE)
        set(${out_reason} "IGHEtherCAT dependency not found" PARENT_SCOPE)
        return()
    endif()
    set(${out_available} TRUE PARENT_SCOPE)
    set(${out_reason} "" PARENT_SCOPE)
endfunction()

set(ENCOS_PLUGIN_CHECK_FUNCTION encos_ethercat_igh_check)
set(ENCOS_PLUGIN_ADAPTER_TYPE "EthercatIGH")
set(ENCOS_PLUGIN_DYNAMIC_TARGET "EthercatIGHPlugin")
set(ENCOS_PLUGIN_STATIC_TARGET "EthercatIGHPluginCore")
set(ENCOS_PLUGIN_STATIC_HEADER "ethercatIGH/ethercat_igh_adapter.h")
set(ENCOS_PLUGIN_STATIC_FACTORY "encos::EthercatIGHAdapter::Create")
set(ENCOS_PLUGIN_VISIBLE ON)
